[build-system]
requires = ["setuptools>=84"]
build-backend = "setuptools.build_meta"

[project]
name = "in_situ_14c"
dynamic = ["version"]
description = "A Python package to compute carbon-14 production in ice"
authors = [{ name = "Walter Cook", email = "wcook8@ur.rochester.edu" }]
license = "BSD-3-Clause"
license-files = ["LICEN[CS]E*"]
readme = {file = "README.md", content-type = "text/markdown"}

requires-python = ">=3.10"

dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "tqdm",
    "mceq",
    "crflux",
    "daemonflux"
]

[project.optional-dependencies]
dev = ["hypothesis", "pytest", "pytest-cov", "coveralls"]
docs = ["numpydoc", "nbsphinx", "ipykernel", "tqdm[notebook]"]

[project.urls]
"Homepage" = "https://github.com/14CO/In-Situ-14C"
"Bug Tracker" = "https://github.com/14CO/In-Situ-14C/issues"

[tool.setuptools.dynamic]
version = {attr = "in_situ_14c.__version__"}

[tool.setuptools.packages.find]
where = ["py"]
include = [
    "in_situ_14c",
    "in_situ_14c.*",
    "in_situ_14c.data.*",
    "in_situ_14c.etc",
]
exclude = [
    "in_situ_14c.scripts",
]

[tool.setuptools.package-data]
"in_situ_14c.data" = ["*.csv"]
"in_situ_14c.data.muon_spectrum_tables" = ["*.csv"]
"in_situ_14c.data.matlab" = ["*.mat", "MC_14CO_mod/*.mat"]
"in_situ_14c.etc" = ["in_situ_14c.rcParams", "*.yaml", "*.ini"]
